{% set name = "onnxruntime" %}
{% set version = "1.9.1" %}
{% set build_number = 1 %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_rev: v{{ version }}
    git_url: https://github.com/microsoft/onnxruntime.git
 
build:
    number: {{ build_number }}
    run_exports:
        - {{ pin_subpackage('onnxruntime', max_pin='x.x') }}

requirements:
    build:
        - python                             # [build_platform != target_platform]
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
    run:

about:
    home: https://onnxruntime.ai/
    license: MIT
    license_file: LICENSE
    summary: Cross-platform, high performance ML inferencing and training accelerator 

